### ISSUE TITLE
Add test cases 

### ISSUE THREAD

**Issue by kmarrip** [chaithanyaMarripati/goSpotify#10]
- Requirement is simple, golang has inbuilt testing library. use that to add test cases

**Comment by krishnaindani** [comment]
hey, I would like to learn more about this and contibute? Would you be able to provide more info on this

**Comment by kmarrip** [comment]
hey @krishnaindani thanks for commenting 
currently there are 4 packages in the repo, it would be great to have test cases written for those. go has a built in testing library 
see this doc for tests https://golang.org/doc/tutorial/add-a-test
just let me know if want to take this up, i will assign it to you.
connect with me on my discord, if anything
Krishna Chaithanya#3728

**Comment by stanipetrosyan** [comment]
Can I work on this if it is not assigned ?

**Comment by kmarrip** [comment]
yep this hasn't been assigned yet. you can work on this @StaniPetrosyan

**Comment by stanipetrosyan** [comment]
Hey, I am almost done with testing cases. I will send a PR on Tuesday because i will be busy in these days. In addiction I  made some refactor on code and gin usage :)
