### ISSUE TITLE
Add state in redirect url and verify it after the auth code is generated 

### ISSUE THREAD

**Issue by kmarrip** [chaithanyaMarripati/goSpotify#7]
- Currently users are redirected without the state param in the url
- Before the users are sent to the authorization server , add a state param as per OIDC standards
- After successful authorization the state is also sent back if given , see the docs [spotify api docs](https://developer.spotify.com/documentation/web-api/)
- This is to stop request forgery

**Comment by mayankagwl** [comment]
@chaithanyaMarripati I like to work on it, can you please assign this to me

**Comment by kmarrip** [comment]
Ok, thanks for showing interest @mayankagwl 
i will assign this to you.
Join the discord server and let me know if you have any issues https://discord.gg/wGXY8zax

**Comment by kmarrip** [comment]
@mayankagwl  any update on this please

**Comment by mayankagwl** [comment]
@chaithanyaMarripati Please review the PR and let me know if there is some issue
and link the PR to this issue
