### ISSUE TITLE
Html page for Failed authentication

### ISSUE THREAD

**Issue by kmarrip** [chaithanyaMarripati/goSpotify#9]
- If the user doesn't authorize the app, authorization server sends back and error in reply url
- Notify the user to accept the permissions

**Comment by nitishapiplani** [comment]
WOULD LIKE TO DO THIS

**Comment by kmarrip** [comment]
Amazing, thanks for showing interest. Will assign this to u. 
Connect with me on discord server, if u are stuck somewhere 
https://discord.gg/wGXY8zax

**Comment by kmarrip** [comment]
@nitishapiplani any update on this issue, if you are facing any issue please contact my via discord.
Thanks

**Comment by nitishapiplani** [comment]
I will do this by today evening

**Comment by nitishapiplani** [comment]
> I will do this by today night

**Comment by kmarrip** [comment]
no pressure @nitishapiplani  
Thanks

**Comment by nitishapiplani** [comment]
sorry will not bbe able to do this you can assign this to anyone else

**Comment by stanipetrosyan** [comment]
Hi, can I work on this ?

**Comment by kmarrip** [comment]
hey you go @StaniPetrosyan , good luck and god speed

**Comment by kmarrip** [comment]
closed by #11
